/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/docs": {
    get: operations["getApiDocs"];
  };
  "/api/docs/json": {
    get: operations["getApiDocsJson"];
  };
  "/api": {
    get: operations["getApi"];
  };
  "/api/teams/{id}": {
    patch: operations["patchApiTeamsById"];
  };
  "/api/groups/{id}": {
    patch: operations["patchApiGroupsById"];
  };
  "/api/users/{id}": {
    get: operations["getApiUsersById"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getApiDocs: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  getApiDocsJson: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  getApi: {
    responses: {
      200: {
        content: never;
      };
    };
  };
  patchApiTeamsById: {
    parameters: {
      path: {
        id: unknown;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          name: string;
        };
        "multipart/form-data": {
          name: string;
        };
        "text/plain": {
          name: string;
        };
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  patchApiGroupsById: {
    parameters: {
      path: {
        id: unknown;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          name: string;
        };
        "multipart/form-data": {
          name: string;
        };
        "text/plain": {
          name: string;
        };
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
  getApiUsersById: {
    parameters: {
      path: {
        id: unknown;
      };
    };
    responses: {
      200: {
        content: never;
      };
    };
  };
}
